[package]
name = "bevy_timeline_editor"
authors = ["markijohn"]
version = "0.1.0"
edition = "2024"
categories = ["rendering"]
description = "Bevy Animation library"
exclude = [".idea"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/markijohn/bevy_timeline"
keywords = ["bevy", "animation"]


[dependencies]
bevy = { version = "0.16", features=["jpeg", "default_font"]}
bevy_egui = { version = "0.36.0"}
bevy_mod_outline = "0.10"
transform-gizmo-bevy = "0.6"
bevy_mod_billboard = {git = "https://github.com/mcobzarenco/bevy_mod_billboard.git", branch = "migrate-0.16"}
bevy_timeline_impls = { path="../bevy_timeline_impls"}
bevy_timeline_runtime = { path= "../bevy_timeline_runtime" }
serde_json = "1"
rfd = "0.15.3"
egui_plot = "0.33.0"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
codegen-units = 1
lto = "thin"
