[package]
name = "bevy_timeline"
version = "0.1.0"
edition = "2024"
categories = ["rendering"]
description = "Bevy Animation library"
exclude = [".idea"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/markijohn/bevy_timeline"
keywords = ["bevy"]

[dependencies]
bevy = "0.16.1"
bevy_egui = {version = "0.34.0-rc.2", optional = true}
thiserror = "2"
serde = "1"

[dev-dependencies]
bevy_obj = "0.16.0"

[features]
timeline_tool = []
rune_expr = []
egui = ["bevy_egui"]
