[package]
name = "bevy_timeline_impls"
authors = ["markijohn"]
version = "0.1.0"
edition = "2024"
categories = ["rendering"]
description = "Bevy Animation library"
exclude = [".idea"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/markijohn/bevy_timeline"
keywords = ["bevy", "animation"]

[dependencies]
bevy_timeline_runtime = { path= "../bevy_timeline_runtime" }
bevy_pbr = "0.16"
bevy_transform = "0.16"
bevy_color = { version = "0.16" }
bevy_math = "0.16"
serde = "1"
serde_json = "1"